### ISSUE TITLE
PM Bar goes outside of div

### ISSUE THREAD

**Issue by rmcgirr83** [VSEphpbb/pmbars#1]
https://github.com/iMattPro/pmbars/blob/6248face2d8c173648cf405c284712d276c00b4d/styles/all/template/event/overall_footer_after.html#L25

Hi Matt,

Many admins have bots that send PM's to people.  They don't necessarily check their outboxes and prune them so they may very well get beyond the 100% limit for messages.  This causes the inner div of this extension to go past the outter div resulting in the attached pic.  I cured this, probably incorrectly by performing this edit in the js.

`percent: {{ FOLDER_PERCENT }} > Math.max(100) ? Math.max(100) : {{ FOLDER_PERCENT }},`

thought you may want to know
![Capture](https://user-images.githubusercontent.com/179079/89774822-2bb9c580-dacc-11ea-878d-36d97aefc87a.PNG)

**Comment by iMattPro** [comment]
I'm not sure how that happens. In my phpBB it puts a hold on excess messages, so it never exceeds 100%

![Screen Shot 2020-09-02 at 10 01 07 AM](https://user-images.githubusercontent.com/303711/92014052-7c0af880-ed03-11ea-9d14-2a72b6ca28e5.png)

But it wouldn't hurt to just add a max-width of 100% to the inner bar.

**Comment by rmcgirr83** [comment]
If the form has a contact bot, like the contact admin extension or a welcome message extension the boxes can exceed the phpBB limits.

**Comment by iMattPro** [comment]
https://github.com/iMattPro/pmbars/commit/a5d4334bbb6d08ebb33a28f540ab4db6a4270753

**Comment by rmcgirr83** [comment]
👍
